on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - shell: bash
        run: ./gradlew lintFdroidDebug
      - shell: bash
        run: ./gradlew lintPlayDebug
      - if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          path: app/build/reports/lint-results-*.html
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - shell: bash
        run: ./gradlew verifySqlDelightMigration
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - shell: bash
        env:
          SIGNING_KEYSTORE_FILE: release.keystore
          SIGNING_KEYSTORE_BASE64: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
          SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ACRA_URI: ${{ secrets.ACRA_URI }}
          ACRA_LOGIN: ${{ secrets.ACRA_LOGIN }}
          ACRA_PASSWORD: ${{ secrets.ACRA_PASSWORD }}
        run: |
          base64 --decode <<< "$SIGNING_KEYSTORE_BASE64" > app/release.keystore
          ./gradlew assembleRelease bundleRelease
      - if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/outputs/apk/*/*/*release*.apk
            app/build/outputs/bundle/*/*release*.aab
            app/build/outputs/mapping/playRelease/mapping.txt
